#!/bin/bash

set -e

rpath="$( dirname "$( realpath "$0" )" )"
cd "$rpath"

function process_theme() {
    theme="$1"
    cd "../themes/$theme"

    echo "// image files for theme $theme" >> ../themes.h
    for screen in initscreen2 miningscreen2 portalscreen btcscreen settingsscreen splashscreen2
    do
        python3 "$rpath/convert_single.py" "${theme}" "./Raw Images/${screen}.png" "${screen}"
#        python3 "$rpath/convert_single.py" "${theme}" "./Raw Images/${screen}.png" "ui_img_${screen}_png.c"
        echo "LV_IMG_DECLARE(ui_img_${theme}_${screen}_png);" >> ../themes.h
        echo "#include \"./${theme}/ui_img_${screen}_png.c\"" >> ../themes.cpp
    done
    echo -e "\n" >> ../themes.h
    echo -e "\n" >> ../themes.cpp
    cd -
}

cd ../themes

cat >themes.h <<EOL
#pragma once

#include "lvgl.h"

// autogenerated, do not modify!

EOL

cp themes.h themes.cpp


while read theme
do
    theme=$( awk -F'/' '{ print $2 }' <<< "$theme")
    [ -z "$theme" ] && continue
    echo $theme
    process_theme "$theme"
done< <(find . -maxdepth 1 -type d)

#python3 convert_single.py ../Raw\ Images/overheat2.png ../ui_img_overheat_png.c


