#pragma once

#include "lvgl.h"

// autogenerated, do not modify!

// image files for theme nerdqaxeplus
LV_IMG_DECLARE(ui_img_nerdqaxeplus_initscreen2_png);
LV_IMG_DECLARE(ui_img_nerdqaxeplus_miningscreen2_png);
LV_IMG_DECLARE(ui_img_nerdqaxeplus_portalscreen_png);
LV_IMG_DECLARE(ui_img_nerdqaxeplus_btcscreen_png);
LV_IMG_DECLARE(ui_img_nerdqaxeplus_settingsscreen_png);
LV_IMG_DECLARE(ui_img_nerdqaxeplus_splashscreen2_png);


// image files for theme nerdoctaxeplus
LV_IMG_DECLARE(ui_img_nerdoctaxeplus_initscreen2_png);
LV_IMG_DECLARE(ui_img_nerdoctaxeplus_miningscreen2_png);
LV_IMG_DECLARE(ui_img_nerdoctaxeplus_portalscreen_png);
LV_IMG_DECLARE(ui_img_nerdoctaxeplus_btcscreen_png);
LV_IMG_DECLARE(ui_img_nerdoctaxeplus_settingsscreen_png);
LV_IMG_DECLARE(ui_img_nerdoctaxeplus_splashscreen2_png);


