#include "lvgl.h"

// autogenerated, do not modify!

#include "./NerdQaxePlus/ui_img_initscreen2_png.c"
#include "./NerdQaxePlus/ui_img_miningscreen2_png.c"
#include "./NerdQaxePlus/ui_img_portalscreen_png.c"
#include "./NerdQaxePlus/ui_img_btcscreen_png.c"
#include "./NerdQaxePlus/ui_img_settingsscreen_png.c"
#include "./NerdQaxePlus/ui_img_splashscreen2_png.c"

#include "./NerdOctaxePlus/ui_img_initscreen2_png.c"
#include "./NerdOctaxePlus/ui_img_miningscreen2_png.c"
#include "./NerdOctaxePlus/ui_img_portalscreen_png.c"
#include "./NerdOctaxePlus/ui_img_btcscreen_png.c"
#include "./NerdOctaxePlus/ui_img_settingsscreen_png.c"
#include "./NerdOctaxePlus/ui_img_splashscreen2_png.c"

